# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-22 08:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming_dispatch', '0002_auto_20160621_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='key',
            field=models.CharField(default='ok', max_length=100),
            preserve_default=False,
        ),
    ]
