# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-22 08:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming_dispatch', '0003_stream_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='server',
            field=models.CharField(default='188.166.151.75', max_length=100),
            preserve_default=False,
        ),
    ]
