# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-22 19:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('streaming_dispatch', '0005_auto_20160622_0824'),
    ]

    operations = [
        migrations.CreateModel(
            name='StreamingServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='stream',
            name='server',
        ),
        migrations.AddField(
            model_name='stream',
            name='sorver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='streaming_dispatch.StreamingServer'),
        ),
    ]
