# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-22 19:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streaming_dispatch', '0006_auto_20160622_1942'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stream',
            old_name='sorver',
            new_name='server',
        ),
    ]
