# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-22 20:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming_dispatch', '0007_auto_20160622_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
